export const USER_ROLES = {
  PASSENGER: "passenger",
  ADMIN: "admin",
  CONTROLLER: "controller",
  SUPERADMIN: "superAdmin",
};
export class User {
  constructor({
    user_id,
    email,
    first_name,
    last_name,
    role,
    token_balance,
    controller_code,
    timestamp,
    password,
    super_admin_code,
    admin_code,
  }) {
    this.user_id = user_id;
    this.email = email;
    this.role = role;
    this.token_balance = token_balance;
    this.controller_code = controller_code;
    this.timestamp = timestamp;
    this.first_name = first_name;
    this.last_name = last_name;
    this.password = password;
    this.super_admin_code = super_admin_code;
    this.admin_code = admin_code;
  }
  /**
   * Rules
   * 1.the id is generated automaticly by supabase at the moment of creation of the new user
   * 2.if the role is passenger or admin or superAdmin the unique code will take NULL
   * 3.if the role is controller the unique code is generated by the admin(randomly)
   * 4.the email for admin will be first_name.admin@gmail.com
   * 5.the email for controller will be first_name.controller@gmail.com
   * 6.the unique code will be a six number code for both
   * 7.if the role is passenger or controller or admin the super_admin_key will be null
   * if the user is not passenger the token_balance will be 0.00
   */
}
