import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const LANGUAGE_STORAGE_KEY = 'admin_language';
export const AdminLanguageContext = createContext(null);

export const TRANSLATIONS = {
	fr: {
		openMenu: 'Ouvrir le menu',
		closeMenu: 'Fermer le menu',
		language: 'Langue',
		settings: 'Paramètres',
		logout: 'Déconnexion',
		mainMenu: 'Menu Principal',
		dashboard: 'Tableau de bord',
		client: 'Client',
		adminManagement: 'Gestion Admin',
		controllerManagement: 'Gestion Contrôleur',
		transport: 'Transport',
		stations: 'Stations',
		routes: 'Routes',
		schedules: 'Horaires',
		ticket: 'Ticket',
		status: 'Statut',
		online: 'En ligne',
		user: 'Utilisateur',
		noEmail: 'Aucun email',
		role_admin: 'Administrateur',
		role_superadmin: 'Super Administrateur',
		role_controller: 'Contrôleur',
		role_passenger: 'Passager',
		total: 'Total',
		actions: 'Actions',
		edit: 'Modifier',
		delete: 'Supprimer',
		cancel: 'Annuler',
		save: 'Enregistrer',
		add: 'Ajouter',
		close: 'Fermer',
		loading: 'Chargement...',
		applyingSession: 'Les modifications sont appliquees sur la session active.',
		transportModule: 'Module Transport',
		transportChooseTitle: 'Choisir le type de transport',
		transportChooseSubtitle: 'Accedez a la gestion des bus ou a la gestion du metro.',
		openBusManagement: 'Ouvrir la gestion bus',
		openMetroManagement: 'Ouvrir la gestion metro',
		routesManagement: 'Gestion des Routes',
		routesSubtitle: 'Configurez les trajets entre stations avec une interface claire.',
		routeName: 'Nom du trajet',
		basePrice: 'Prix de base',
		startStation: 'Station depart',
		endStation: 'Station arrivee',
		selectPlaceholder: 'Selectionner...',
		addRoute: 'Ajouter Trajet',
		updateItem: 'Mettre a jour',
		cancelEdit: 'Annuler Edition',
		emptyRoutes: 'Aucun trajet trouve.',
		schedulesManagement: 'Gestion des Horaires',
		schedulesSubtitle: 'Planifiez les departs et arrivees sur les routes existantes.',
		routeLabel: 'Trajet (Route)',
		departureTime: 'Heure de depart',
		arrivalTime: "Heure d'arrivee",
		priceCurrent: 'Prix (current_price)',
		delayedMinutes: 'Retard (minutes)',
		remarkClient: 'Remarque (visible client)',
		addSchedule: 'Ajouter Horaire',
		emptySchedules: 'Aucune planification trouvee.',
		onTime: "A l'heure",
		delayed: 'En retard',
		stationsManagement: 'Gestion des Stations',
		stationsSubtitle: 'Ajoutez, modifiez et organisez les stations selon votre reseau.',
		editStation: 'Modifier une station',
		addStation: 'Ajouter une station',
		editMode: 'Mode edition',
		stationName: 'Nom de la station',
		emptyStations: 'Aucune station trouvee.',
		employeesModule: 'Module Employes',
		searchByIdNameEmail: 'Rechercher par ID, nom ou email',
		newAction: 'Nouveau',
		accountCreatedSuccess: 'Compte cree avec succes',
		codeToEnter: 'Code a saisir',
		keepCodeInstruction: 'Conservez ce code et saisissez-le lors de la deuxieme connexion.',
		createNewAccount: 'Creer un nouveau compte',
		updateEmployeeInfo: 'Mettez a jour les informations ci-dessous. Laissez le mot de passe vide pour le conserver.',
		fillFieldsToAddUser: 'Remplissez les champs pour ajouter cet utilisateur au systeme.',
		firstName: 'Prenom',
		secondName: 'Nom',
		password: 'Mot de passe',
		passwordOptional: '(optionnel)',
		saving: 'Enregistrement...',
		saveChanges: 'Enregistrer les modifications',
		cancelEditLong: "Annuler l'edition",
		itemsCountEmployees: 'employe(s)',
		loadingData: 'Chargement des donnees...',
		emptyEmployees: 'Aucun employe trouve.',
		accountSettingsArea: 'Espace Parametres',
		accountSettingsTitle: 'Parametres du Compte',
		fieldPenHint: 'Le changement se fait avec le stylo de chaque champ.',
		profile: 'Profil',
		dataSource: 'Source des donnees',
		dataSourceLine1: 'Les champs ci-dessous sont maintenant modifiables.',
		dataSourceLine2: "Le code de reference n'est plus affiche.",
		dataSourceLine3: 'Role et identifiant restent en lecture seule.',
		fullName: 'Nom complet',
		editFullName: 'Modifier nom complet',
		editEmail: 'Modifier email',
		role: 'Role',
		identifier: 'Identifiant',
		back: 'Retour',
		superAdminAccess: 'Acces Super Admin',
		restrictedZone: 'Zone reservee aux administrateurs',
		destination: 'Destination',
		controllers: 'Controleurs',
		admins: 'Admins',
		superAdminPassword: 'Mot de passe super admin',
		enterPassword: 'Entrez le mot de passe',
		accessControllerManagement: 'Acceder a la gestion controleur',
		accessAdminManagement: 'Acceder a la gestion admin',
		unauthorizedAttempts: "Tentatives d'acces non autorisees sont enregistrees",
		requiredPassword: 'Le mot de passe est obligatoire',
		incorrectPassword: 'Mot de passe incorrect',
		accessGranted: 'Acces autorise! Bienvenue super admin',
		dashboardLabel: 'Tableau de bord',
		transportPerformance: 'Performance transport',
		revenueDateTransactions: 'Revenus du {date} | {count} transactions',
		transactions: 'Transactions',
		variation: 'Variation',
		totalUsers: 'Utilisateurs Totaux',
		totalRevenueGlobal: 'Revenu total (Global)',
		totalFleet: 'Flotte totale',
		metrosAndBuses: '{metros} metros et {buses} bus',
		metroSeatsSold: 'Places vendues metro',
		busSeatsSold: 'Places vendues bus',
		quickActions: 'Actions rapides',
		administration: 'Administration',
		addOrEditStations: 'Ajouter ou modifier les stations',
		configureRoutes: 'Configurer les trajets',
		planDepartures: 'Planifier les departs',
		manageActiveFleet: 'Gerer la flotte active',
		revenueSplit: 'Repartition revenus',
		busVsMetro: 'Bus vs Metro',
		metroInService: 'Metro en service',
		busInService: 'Bus en service',
		trainsets: 'rames',
		increase: 'Hausse',
		decrease: 'Baisse',
		transportTracking: 'Suivi des {entity} et operations',
		activePlural: 'Actifs',
		list: 'Liste',
		emptyElements: 'Aucun element disponible. Cliquez sur Ajouter pour commencer.',
		requiredFields: 'Champs obligatoires.',
		occupancyRange: 'Charge entre 0 et 100.',
		codeAlreadyUsed: 'Code deja utilise.',
		unexpectedError: 'Une erreur est survenue.',
		addEntity: 'Ajouter un {entity}',
		editEntity: 'Modifier un {entity}',
		clientModule: 'Module Client',
		clientControl: 'Controle des clients',
		clientControlSubtitle: 'Gerer les clients et leurs IDs ticket rapidement.',
		clientSearch: 'Recherche client',
		clientSearchPlaceholder: 'ID client, nom, email ou token',
		clientsCount: 'client(s)',
		loadingClients: 'Chargement des clients en cours...',
		emptyClients: 'Aucun client trouve.',
		clientLabel: 'Client',
		clientEmail: 'E-mail Client',
		signupDate: "Date d'inscription",
		editClient: 'Modifier ce client',
		emailAddress: 'Adresse e-mail',
		userRole: "Role de l'utilisateur",
		tokenBalance: 'Solde token',
		deleteClientConfirm: 'Voulez-vous vraiment supprimer ce client ?',
		deleteClientError: 'Erreur lors de la suppression du client.',
		ticketModule: 'Module Ticket',
		soldTickets: 'Tickets vendus',
		soldTicketsSubtitle: 'Affichez les tickets vendus et filtrez-les selon vos criteres.',
		simpleSearch: 'Recherche simple',
		all: 'Tous',
		searchByRoute: 'Par trajet',
		searchById: 'Par ID',
		searchByDate: 'Par date',
		searchByStatus: 'Par statut',
		searchByType: 'Par type',
		typeSearch: 'Tapez votre recherche',
		ticketsCount: 'ticket(s)',
		loadingTickets: 'Chargement des tickets en cours...',
		emptyTickets: 'Aucun ticket trouve.',
		clientTicket: 'Ticket client',
		typeLabel: 'Type',
		routeLabelSimple: 'Trajet',
		purchaseTripDate: 'Achat & Date de voyage',
		editTicket: 'Modifier ce ticket',
		unknown: 'Inconnu',
		sold: 'Vendu',
		passenger: 'Passager',
	},
	en: {
		openMenu: 'Open menu',
		closeMenu: 'Close menu',
		language: 'Language',
		settings: 'Settings',
		logout: 'Logout',
		mainMenu: 'Main Menu',
		dashboard: 'Dashboard',
		client: 'Client',
		adminManagement: 'Admin Management',
		controllerManagement: 'Controller Management',
		transport: 'Transport',
		stations: 'Stations',
		routes: 'Routes',
		schedules: 'Schedules',
		ticket: 'Ticket',
		status: 'Status',
		online: 'Online',
		user: 'User',
		noEmail: 'No email',
		role_admin: 'Administrator',
		role_superadmin: 'Super Administrator',
		role_controller: 'Controller',
		role_passenger: 'Passenger',
		total: 'Total',
		actions: 'Actions',
		edit: 'Edit',
		delete: 'Delete',
		cancel: 'Cancel',
		save: 'Save',
		add: 'Add',
		close: 'Close',
		loading: 'Loading...',
		applyingSession: 'Changes are applied to the active session.',
		transportModule: 'Transport Module',
		transportChooseTitle: 'Choose transport type',
		transportChooseSubtitle: 'Access bus management or metro management.',
		openBusManagement: 'Open bus management',
		openMetroManagement: 'Open metro management',
		routesManagement: 'Routes Management',
		routesSubtitle: 'Configure routes between stations with a clear interface.',
		routeName: 'Route name',
		basePrice: 'Base price',
		startStation: 'Start station',
		endStation: 'End station',
		selectPlaceholder: 'Select...',
		addRoute: 'Add Route',
		updateItem: 'Update',
		cancelEdit: 'Cancel Edit',
		emptyRoutes: 'No routes found.',
		schedulesManagement: 'Schedules Management',
		schedulesSubtitle: 'Plan departures and arrivals on existing routes.',
		routeLabel: 'Route',
		departureTime: 'Departure time',
		arrivalTime: 'Arrival time',
		priceCurrent: 'Price (current_price)',
		delayedMinutes: 'Delay (minutes)',
		remarkClient: 'Remark (client visible)',
		addSchedule: 'Add Schedule',
		emptySchedules: 'No schedules found.',
		onTime: 'On time',
		delayed: 'Delayed',
		stationsManagement: 'Stations Management',
		stationsSubtitle: 'Add, edit, and organize stations across your network.',
		editStation: 'Edit a station',
		addStation: 'Add a station',
		editMode: 'Edit mode',
		stationName: 'Station name',
		emptyStations: 'No stations found.',
		employeesModule: 'Employees Module',
		searchByIdNameEmail: 'Search by ID, name or email',
		newAction: 'New',
		accountCreatedSuccess: 'Account created successfully',
		codeToEnter: 'Code to enter',
		keepCodeInstruction: 'Keep this code and enter it on the second login.',
		createNewAccount: 'Create a new account',
		updateEmployeeInfo: 'Update the information below. Leave password empty to keep it unchanged.',
		fillFieldsToAddUser: 'Fill out the fields to add this user to the system.',
		firstName: 'First name',
		secondName: 'Last name',
		password: 'Password',
		passwordOptional: '(optional)',
		saving: 'Saving...',
		saveChanges: 'Save changes',
		cancelEditLong: 'Cancel editing',
		itemsCountEmployees: 'employee(s)',
		loadingData: 'Loading data...',
		emptyEmployees: 'No employees found.',
		accountSettingsArea: 'Settings Area',
		accountSettingsTitle: 'Account Settings',
		fieldPenHint: 'Changes are made with each field pen button.',
		profile: 'Profile',
		dataSource: 'Data source',
		dataSourceLine1: 'Fields below are now editable.',
		dataSourceLine2: 'Reference code is no longer displayed.',
		dataSourceLine3: 'Role and identifier remain read-only.',
		fullName: 'Full name',
		editFullName: 'Edit full name',
		editEmail: 'Edit email',
		role: 'Role',
		identifier: 'Identifier',
		back: 'Back',
		superAdminAccess: 'Super Admin Access',
		restrictedZone: 'Administrators only area',
		destination: 'Destination',
		controllers: 'Controllers',
		admins: 'Admins',
		superAdminPassword: 'Super admin password',
		enterPassword: 'Enter password',
		accessControllerManagement: 'Access controller management',
		accessAdminManagement: 'Access admin management',
		unauthorizedAttempts: 'Unauthorized access attempts are logged',
		requiredPassword: 'Password is required',
		incorrectPassword: 'Incorrect password',
		accessGranted: 'Access granted! Welcome super admin',
		dashboardLabel: 'Dashboard',
		transportPerformance: 'Transport performance',
		revenueDateTransactions: 'Revenue on {date} | {count} transactions',
		transactions: 'Transactions',
		variation: 'Variation',
		totalUsers: 'Total users',
		totalRevenueGlobal: 'Total revenue (Global)',
		totalFleet: 'Total fleet',
		metrosAndBuses: '{metros} metros and {buses} buses',
		metroSeatsSold: 'Metro seats sold',
		busSeatsSold: 'Bus seats sold',
		quickActions: 'Quick actions',
		administration: 'Administration',
		addOrEditStations: 'Add or edit stations',
		configureRoutes: 'Configure routes',
		planDepartures: 'Plan departures',
		manageActiveFleet: 'Manage active fleet',
		revenueSplit: 'Revenue split',
		busVsMetro: 'Bus vs Metro',
		metroInService: 'Metro in service',
		busInService: 'Bus in service',
		trainsets: 'trainsets',
		increase: 'Increase',
		decrease: 'Decrease',
		transportTracking: 'Tracking {entity} and operations',
		activePlural: 'Active',
		list: 'List',
		emptyElements: 'No items available. Click Add to get started.',
		requiredFields: 'Required fields.',
		occupancyRange: 'Load must be between 0 and 100.',
		codeAlreadyUsed: 'Code already used.',
		unexpectedError: 'An unexpected error occurred.',
		addEntity: 'Add a {entity}',
		editEntity: 'Edit a {entity}',
		clientModule: 'Client Module',
		clientControl: 'Client Control',
		clientControlSubtitle: 'Manage clients and their ticket IDs quickly.',
		clientSearch: 'Client search',
		clientSearchPlaceholder: 'Client ID, name, email or token',
		clientsCount: 'client(s)',
		loadingClients: 'Loading clients...',
		emptyClients: 'No clients found.',
		clientLabel: 'Client',
		clientEmail: 'Client e-mail',
		signupDate: 'Signup date',
		editClient: 'Edit this client',
		emailAddress: 'Email address',
		userRole: 'User role',
		tokenBalance: 'Token balance',
		deleteClientConfirm: 'Do you really want to delete this client?',
		deleteClientError: 'Error while deleting client.',
		ticketModule: 'Ticket Module',
		soldTickets: 'Sold tickets',
		soldTicketsSubtitle: 'View sold tickets and filter them by your criteria.',
		simpleSearch: 'Simple search',
		all: 'All',
		searchByRoute: 'By route',
		searchById: 'By ID',
		searchByDate: 'By date',
		searchByStatus: 'By status',
		searchByType: 'By type',
		typeSearch: 'Type your search',
		ticketsCount: 'ticket(s)',
		loadingTickets: 'Loading tickets...',
		emptyTickets: 'No tickets found.',
		clientTicket: 'Client ticket',
		typeLabel: 'Type',
		routeLabelSimple: 'Route',
		purchaseTripDate: 'Purchase & trip date',
		editTicket: 'Edit this ticket',
		unknown: 'Unknown',
		sold: 'Sold',
		passenger: 'Passenger',
	},
};

export const getInitialLanguage = () => {
	if (typeof window === 'undefined') {
		return 'fr';
	}

	try {
		const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
		if (stored === 'fr' || stored === 'en') {
			return stored;
		}
	} catch {
		// Ignore storage access errors and fallback to browser language.
	}

	const browserLanguage = window.navigator?.language?.toLowerCase() || '';
	return browserLanguage.startsWith('en') ? 'en' : 'fr';
};

export const persistLanguage = (language) => {
	if (typeof window === 'undefined') {
		return;
	}

	try {
		window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
	} catch {
		// Ignore storage access errors.
	}
};

export const translateText = (language, key, fallback = key, params = null) => {
	const dict = TRANSLATIONS[language] || TRANSLATIONS.fr;
	let value = dict[key] || fallback;
	if (params && typeof value === 'string') {
		Object.entries(params).forEach(([paramKey, paramValue]) => {
			value = value.replaceAll(`{${paramKey}}`, String(paramValue));
		});
	}
	return value;
};

export const useAdminLanguage = () => {
	const context = useContext(AdminLanguageContext);
	if (context) {
		return context;
	}

	const [language, setLanguage] = useState(getInitialLanguage);

	useEffect(() => {
		if (typeof document !== 'undefined') {
			document.documentElement.lang = language;
		}
		persistLanguage(language);
	}, [language]);

	const t = useMemo(
		() => (key, fallback = key, params = null) => translateText(language, key, fallback, params),
		[language]
	);

	return { language, setLanguage, t };
};

export const AdminLanguageProvider = ({ children }) => {
	const [language, setLanguage] = useState(getInitialLanguage);

	useEffect(() => {
		if (typeof document !== 'undefined') {
			document.documentElement.lang = language;
		}
		persistLanguage(language);
	}, [language]);

	const t = useMemo(
		() => (key, fallback = key, params = null) => translateText(language, key, fallback, params),
		[language]
	);

	const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

	return <AdminLanguageContext.Provider value={value}>{children}</AdminLanguageContext.Provider>;
};
